kind: pipeline
type: docker
name: build-container

steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: git.clortox.com/infrastructure/filebrowser
    registry: git.clortox.com
    username:
      from_secret: gitea_docker_username
    password:
      from_secret: gitea_docker_password
    tags:
      - latest
      - ${DRONE_TAG}
    when:
      event:
        - tag

- name: notify
  image: clortox/drone-ntfy
  settings:
    URL: https://ntfy.clortox.com
    USERNAME: drone
    PASSWORD:
      from_secret: ntfy_password
    TOPIC: drone-builds
    MESSAGE: Filebrowser ${DRONE_TAG} has compiled!
    CLICK: https://drone.clortox.com/Infrastructure/filebrowser
    TITLE: Filebrowser
  when:
    event:
      - tag


trigger:
  event:
    - tag
