name: Build and push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: git.clortox.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            git.clortox.com/infrastructure/filebrowser:latest
            git.clortox.com/infrastructure/filebrowser:${{ github.ref_name }}
